# Generated by Django 3.1.3 on 2020-12-11 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashvalue', models.CharField(max_length=50, unique=True)),
                ('path', models.FilePathField(unique=True)),
                ('format', models.CharField(max_length=4)),
                ('url', models.URLField(unique=True)),
                ('thumbnail', models.URLField(unique=True)),
                ('reported', models.BooleanField(default=False)),
                ('query', models.CharField(max_length=50)),
                ('download_url', models.URLField(unique=True)),
                ('download_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PictureOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.gallery')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.picture')),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='pictures',
            field=models.ManyToManyField(through='pictures.PictureOrder', to='pictures.Picture'),
        ),
    ]
