# Generated by Django 3.1.3 on 2020-11-27 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='user',
            new_name='owner',
        ),
    ]
