# Generated by Django 3.1.3 on 2020-11-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20201127_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='hashvalue',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
