# Generated by Django 3.1.3 on 2020-11-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_auto_20201129_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='thumbnail',
            field=models.URLField(default='http://images.dailypicture.xyz/824332fd48f1b4726cb82b6ed.thumbnail.png', unique=True),
            preserve_default=False,
        ),
    ]
